# Generated by Django 3.1.7 on 2021-03-01 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_date_joined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
