# Generated by Django 3.1.7 on 2021-03-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='username',
        ),
    ]
