# Generated by Django 3.1.7 on 2021-03-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
