# Generated by Django 3.1.7 on 2021-03-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
