# Generated by Django 3.1.7 on 2021-03-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
