# Generated by Django 3.1.7 on 2021-03-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='profile_cover/coverdefault.jpg', upload_to='profile_cover/'),
        ),
    ]
