# Generated by Django 3.1.7 on 2021-03-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20210303_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default='blog/thumbnail/default.png', upload_to=''),
        ),
    ]
