# Generated by Django 3.1.7 on 2021-03-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, default='blog/thumbnail/default.png', upload_to=''),
        ),
    ]
