# Generated by Django 3.1.7 on 2021-03-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_blog_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='images',
            field=models.ImageField(upload_to='blog/cover/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, default='blog/thumbnail/default.png', upload_to='blog/thumbnail'),
        ),
    ]
