# Generated by Django 3.1.7 on 2021-03-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20210303_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
    ]
