# Generated by Django 3.1.7 on 2021-03-08 14:19

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Django', 'Django'), ('React', 'React'), ('Laravel', 'Lavarel'), ('Angular', 'Angular')], default='Django', max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=656)),
                ('cover', models.ImageField(blank=True, upload_to='group_cover/')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Close', 'Close')], max_length=50)),
                ('admin', models.ManyToManyField(related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.category')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
