# Generated by Django 3.1.7 on 2021-03-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Django', 'Django'), ('React', 'React'), ('Laravel', 'Lavarel'), ('Angular', 'Angular')], default='Django', max_length=56, null=True),
        ),
    ]
