# Generated by Django 3.1.7 on 2021-03-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210309_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='category',
            field=models.CharField(blank=True, choices=[('Django', 'Django'), ('React', 'React'), ('Laravel', 'Lavarel'), ('Angular', 'Angular')], max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
