# Generated by Django 3.1.7 on 2021-03-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20210302_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cover',
            field=models.ImageField(blank=True, upload_to='group_cover/'),
        ),
    ]
