# Generated by Django 3.1.7 on 2021-03-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20210309_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Django', 'Django'), ('React', 'React'), ('Laravel', 'Lavarel'), ('Angular', 'Angular')], max_length=20),
        ),
    ]
