# Generated by Django 3.1.7 on 2021-03-05 02:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20210304_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
