# Generated by Django 3.1.7 on 2021-03-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20210305_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Close', 'Close')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
