# Generated by Django 3.1.7 on 2021-03-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('django', 'django'), ('react', 'react'), ('laravel', 'lavarel'), ('angular', 'angular')], max_length=20),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='body',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
