# Generated by Django 3.1.7 on 2021-03-06 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_group_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='groups.group'),
        ),
    ]
