# Generated by Django 3.1.7 on 2021-03-10 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20210310_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='categories',
        ),
        migrations.AddField(
            model_name='grouppost',
            name='categories',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.category'),
        ),
    ]
