# Generated by Django 3.1.7 on 2021-03-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20210310_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.category'),
        ),
    ]
